### ISSUE TITLE
 Wolfenstein 2 via Wine Staging or new Wine Vulkan project doesnt' work vs AMDGPU Pro that works..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Drivers/AMDVLK#9] opened 2018-02-03 13:08 UTC
Hi,
just tested Wolfenstein 2 (Vulkan game) via new Wine Vulkan wrapper (https://github.com/roderickc/wine-vulkan) and Wine Staging 2.21 (needs Staging for Vulkan "passtrough" and +2patches (ntdll patch+vulkan patch) from (https://bugs.winehq.org/show_bug.cgi?id=43935) to fix Wolf2 issues) (note roderickc wine vulkan Project doesn't need any as is based on Wine 3.0 that includes ntdll patch and doesn't need vulkan patch) using AMDGPU Pro closed driver 17.50 (reports Vulkan 2.0.2 driver) on RX Vega 56 and it worked nice similar to same procedure on Nvidia GPU with Nvidia closed driver for Linux..
even AMD RADV from oibaf PPA with RX Vega works altough some graphical issues exist there..

anyway using open source AMDVLK doesn't play so nice..
using first code drop from last year (reports Vulkan 2.0.0) at least game launched correctly up to menu rendering OK but and game loads saved game correct until I saw in game GUI elements and sound as if game was ready for play but screen was black..
using latest code drop as of 1february or so (reports as Vulkan 2.0.11) game fails to launch saying missing extensions which is strange as this driver supports more extensions than before still not as much as AMDGPU PRO closed driver.. see my three reports here:
http://vulkan.gpuinfo.org/compare.php?compare=compare&id%5B2531%5D=on&id%5B2508%5D=on&id%5B2267%5D=on
see extesions supported is 40 in AMDGPU PRO (2.0.2) 23 on 2.0.0 driver and 29 on latest drop (driver 2.0.11)..

hope AMDVLK can run eventually Wolfenstein 2 via Wine without issues on RX Vega as AMDGPU Pro driver..

**Comment by jinjianrong** [comment] 2018-04-03 03:51
@oscarbg The issue is fixed in latest code, please give it a try

**Closed by jinjianrong** 2018-04-03 03:51 UTC
Labels: assigned
