### ISSUE TITLE
AMDVLK fails to initialize (in createInstance) with a navi and a pre-navi GPU

### ISSUE THREAD

**Issue by BNieuwenhuizen** [GPUOpen-Drivers/AMDVLK#107] opened 2019-08-11 00:36 UTC
Caused by different LLVM arguments.

-amdgpu-atomic-optimizations in only set for pre-gfx10, so if you mix LLPC will complain about differing arguments and fail to initialize second GPU.

AMDVLK then completely fails CreateInstance, instead of degrading to only exposing the first GPU.

**Comment by linqun** [comment] 2019-08-12 02:37
Thank you for catching this issue. 
- please disable -amdgpu-atomic-optimizations  as a workaround.
- -amdgpu-atomic-optimizations will be supported on navi10 soon.  and until now, it is the only option which dependent on gfxip.

**Comment by jinjianrong** [comment] 2019-08-14 07:07
The issue is fixed in latest code

**Closed by jinjianrong** 2019-08-14 07:07 UTC
