### ISSUE TITLE
Starfield unsupported  graphics card

### ISSUE THREAD

**Issue by oldeschool** [GPUOpen-Drivers/AMDVLK#333] opened 2023-09-03 00:55 UTC
on Ubuntu 22.04.3 LTS  with an AMD 7900 XT
Starfield fails to start with pop up message -- graphics card does not meet the minimal specification requirements.

runs and plays using radv -- no start with AMDVLK

**Comment by oldeschool** [comment] 2023-11-21 01:13
problem persists with 2023.Q4.1

**Comment by JoeLiu-SH** [comment] 2023-11-28 09:05
This issue is not caused by Ubuntu or AMD graphics cards. It is because of VKD3D uses the VK_NV_device_ generated_commands function, which is a vender specific extension (not a Khronos standard yet). Khronos has a new version under discussion: https://gitlab.khronos.org/vulkan/vulkan/-/blob/VK_EXT_device_generated_commands/proposals/VK_EXT_device_generated_commands.adoc RADV partially implements VK_NV_device_ generated_commands so it works.

**Comment by Degerz** [comment] 2023-11-29 04:54
@JoeLiu-SH Khronos Group would prefer it's participants to not reveal any information prior to official disclosure ...

**Comment by JoeLiu-SH** [comment] 2023-11-29 07:59
@Degerz Thanks for your reminder, I just updated the comment and removed the link.

**Comment by Degerz** [comment] 2023-11-29 08:17
@JoeLiu-SH Better to delete the comment altogether since it'll show up in edit history ...

**Comment by JoeLiu-SH** [comment] 2023-11-29 09:26
This issue is because of VKD3D uses the VK_NV_device_ generated_commands function, which is vender specific extension (not a Khronos standard yet). RADV partially implements this extension so it works.

**Comment by jinjianrong** [comment] 2024-05-17 01:27
Fixed in 2024.Q2.1

**Closed by jinjianrong** 2024-05-17 01:27 UTC
