### ISSUE TITLE
Doom 2016 crashes after a while

### ISSUE THREAD

**Issue by ZerataX** [GPUOpen-Drivers/AMDVLK#175] opened 2020-07-23 00:58 UTC
Playing Doom 2016 with RADV works perfectly fine and even amdvlk seems to work great with improved performance until you reach a certain point in the game when it suddenly crashes. most of the time when starting a new campaign it happens when I pick up the helmet.
When the game crashes the music still continues and I can see my mouse, but I can't alt-tab and after a while the frozen image gets replaced by something like this:

![IMG_20200723_024221](https://user-images.githubusercontent.com/5024958/88243010-4f3cdd80-cc8f-11ea-883b-fa26d2276c92.jpg)
after a while I press the power button which then results in this:

![IMG_20200723_024410](https://user-images.githubusercontent.com/5024958/88243019-5a900900-cc8f-11ea-93e4-32e9e47afbac.jpg)

I sometimes recover the session like this and the display-manager/x-server restarts.
I tried starting from different saves I had and with different resolutions and settings, but it always crashes a few minutes in.

Also maybe interesting, but Doom eternal doesn't seem to crash, but I've only yet tried 30minutes.

I can't use renderdoc when the game crashes, but I created a capture before it crashes if that's from any interest:
[RenderDoc.tar.gz](https://dmnd.sh/public/RenderDoc.tar.gz)
here is my steam proton log and vulkaninfo output:
[vulkaninfo and protonlog.tar.gz](https://github.com/GPUOpen-Drivers/AMDVLK/files/4963378/vulkaninfo.and.protonlog.tar.gz)
I have [mangohud](https://github.com/flightlessmango/MangoHud/) installed, which might be reported in these logs, but deinstalling it doesn't seem to change anything.

This part from the log of my display-manager around it restarting also seems interesting:

<details>
<summary><a href="https://github.com/GPUOpen-Drivers/AMDVLK/files/4963417/display-manager.log">display-manager.log</a></summary>

```
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: amdgpu: command stream overflowed
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE)
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) Backtrace:
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 0: /nix/store/nwhyzvn30nnhjk9yrh1zb7nc90hzd8d2-xorg-server-1.20.8/bin/X (OsSigHandler+0x28) [0x59bba8]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 1: /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libpthread.so.0 (funlockfile+0x50) [0x7f1dce8aefbf]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 2: /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libc.so.6 (_int_malloc+0xd3a) [0x7f1dce75ef4a]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 3: /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libc.so.6 (__libc_calloc+0x81) [0x7f1dce760ca1]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 4: /run/opengl-driver/lib/dri/radeonsi_dri.so (amdgpu_cs_create+0x3c) [0x7f1dccff1ecc]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 5: /run/opengl-driver/lib/dri/radeonsi_dri.so (si_create_context+0x200) [0x7f1dccf71f60]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 6: /run/opengl-driver/lib/dri/radeonsi_dri.so (si_get_reset_status+0xb0) [0x7f1dccf72870]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 7: /run/opengl-driver/lib/dri/radeonsi_dri.so (si_flush_gfx_cs+0x74) [0x7f1dccfdcfc4]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 8: /run/opengl-driver/lib/dri/radeonsi_dri.so (si_flush_from_st+0xd0) [0x7f1dccfdb140]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 9: /run/opengl-driver/lib/dri/radeonsi_dri.so (st_glFlush+0x14) [0x7f1dcc88dc54]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 10: /nix/store/gzv9gfbxvdw0icjqnqdjqm4150wkfynm-mesa-20.0.8-drivers/lib/libEGL_mesa.so.0 (dri2_make_current+0x96) [0x7f1db45d1>
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 11: /nix/store/gzv9gfbxvdw0icjqnqdjqm4150wkfynm-mesa-20.0.8-drivers/lib/libEGL_mesa.so.0 (eglMakeCurrent+0x139) [0x7f1db45c03f>
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 12: /nix/store/815cqvzqysx0k8kahl472d8f0k5ss5yx-libGL-1.3.1/lib/libEGL.so.1 (InternalLoseCurrent+0x4c) [0x7f1dc40219bc]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 13: /nix/store/nwhyzvn30nnhjk9yrh1zb7nc90hzd8d2-xorg-server-1.20.8/lib/xorg/modules/libglamoregl.so (glamor_egl_make_current+0>
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 14: /nix/store/nwhyzvn30nnhjk9yrh1zb7nc90hzd8d2-xorg-server-1.20.8/lib/xorg/modules/libglamoregl.so (_glamor_block_handler+0x4>
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 15: /nix/store/nwhyzvn30nnhjk9yrh1zb7nc90hzd8d2-xorg-server-1.20.8/lib/xorg/modules/drivers/modesetting_drv.so (msBlockHandler>
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 16: /nix/store/nwhyzvn30nnhjk9yrh1zb7nc90hzd8d2-xorg-server-1.20.8/bin/X (BlockHandler+0x78) [0x445ee8]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 17: /nix/store/nwhyzvn30nnhjk9yrh1zb7nc90hzd8d2-xorg-server-1.20.8/bin/X (WaitForSomething+0x11a) [0x5954ea]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 18: /nix/store/nwhyzvn30nnhjk9yrh1zb7nc90hzd8d2-xorg-server-1.20.8/bin/X (Dispatch+0xb3) [0x4412e3]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 19: /nix/store/nwhyzvn30nnhjk9yrh1zb7nc90hzd8d2-xorg-server-1.20.8/bin/X (dix_main+0x374) [0x445524]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 20: /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libc.so.6 (__libc_start_main+0xeb) [0x7f1dce6fed8b]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) 21: /nix/store/nwhyzvn30nnhjk9yrh1zb7nc90hzd8d2-xorg-server-1.20.8/bin/X (_start+0x2a) [0x42f33a]
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE)
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) Segmentation fault at address 0x20000000000d
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE)
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: Fatal server error:
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE) Caught signal 11 (Segmentation fault). Server aborting
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE)
Jul 23 02:44:16 gestalt xserver-wrapper[1083]: (EE)
```
</details>

```
OS: NixOS 20.09 (Nightingale) x86_64 
Kernel: 5.4.51 
DE: Plasma (x11)
CPU: Intel i7-9700K (8) @ 4.900GHz 
GPU: NVIDIA P106-100 
GPU: AMD ATI Radeon RX Vega 56 (amdvlk 2020.Q3.1)
```

**Edit:** wayland also seems to behave the same

**Comment by ZerataX** [comment] 2020-07-29 23:35
update: 2020.Q3.2 still behaves exactly the same

**Comment by jinjianrong** [comment] 2020-08-04 08:02
It is a regression caused by [PR650] Rationalized user data usage

**Comment by ZerataX** [comment] 2020-08-15 02:54
seems like with 2020.Q3.3 this is fixed? I've played for roughly 30min and no crashes, so I'm going to close this issue now

**Comment by ZerataX** [comment] 2020-08-16 20:23
Sorry that was wrong, I accidentally deleted the amdvlk icd file so I just started doom with radv instead of amdvlk. This issue is obviously still present with 2020.Q3.3

**Comment by jinjianrong** [comment] 2020-08-17 04:45
Fixed in llpc dev branch with https://github.com/GPUOpen-Drivers/llpc/commit/44a8e50f5211fd718a2724e88e827e2e952d6fbf

**Comment by JaxLinAMD** [comment] 2020-08-20 09:24
GPUOpen-Drivers/llpc@44a8e50 will be promoted to master branch at v-2020.Q3.5( not v-2020.Q3.4)

**Comment by JaxLinAMD** [comment] 2020-09-15 03:37
@ZerataX  issue fixed in v-2020.Q3.5 please verify that, thanks!

**Closed** 2020-09-16 05:50 UTC
Labels: fixed

**Comment by ZerataX** [comment] 2020-09-17 02:36
yay it does work! and also 10% faster than radv so that is also super cool
https://flightlessmango.com/games/6406/logs/735
