### ISSUE TITLE
vkAcquireNextImageKHR returning VK_TIMEOUT w/o waiting the timeout duration

### ISSUE THREAD

**Issue by mikedilger** [GPUOpen-Drivers/AMDVLK#15] opened 2018-02-27 06:56 UTC
I've been able to cause a condition where vkAcquireNextImageKHR returns VK_TIMEOUT.  It's not the first frame, but rather near the first frame (maybe the second, third, or fourth).

The timeout parameter passed to that function has been 4000000000 nanoseconds (4 seconds).  Yet my renderer comes up and crashes all within about half a second, so it's clearly not waiting 4 seconds.

I can get the renderer to work in other conditions, and I'm not concerned about the condition that causes this, just about it's handling.  After all, it's quite possible that I haven't quite fulfilled the synchronization requirements, in which case it would technically be my fault.

However, IMHO, vkAcquireNextImageKHR shouldn't return VK_TIMEOUT unless it was actually a timeout. It should return an appropriate error if it was an error.

Vulkan layers report no warnings or errors.

**Comment by mikedilger** [comment] 2018-02-27 07:06
I would attach a trace but I can't seem to get the behavior to repeat when I run it under vktrace.

**Comment by davidmaoamd** [comment] 2018-02-27 09:47
Hi Dilger,
You might run into the case that the semaphore wait got interrupted or returned with some unexpected error.
I agree we’d better to improve this to handle those corner case correctly.
We will make the change.

Thanks.
Best Regards,
David

**Comment by davidmaoamd** [comment] 2018-02-27 09:48
Hi Dilger,
You might run into the case that the semaphore wait got interrupted or returned with some unexpected error.
I agree we’d better to improve this to handle those corner case correctly.
We will make the change.

Thanks.
Best Regards,
David

**Comment by jinjianrong** [comment] 2018-05-15 08:01
@mikedilger could you verify if the issue is fixed in latest code? thanks

**Closed** 2018-05-15 08:01 UTC
Labels: fixed, fixed internally
