### ISSUE TITLE
Garbled graphics

### ISSUE THREAD

**Issue by MojoJojoDojo** [GPUOpen-Drivers/AMDVLK#72] opened 2019-01-02 22:48 UTC
GPU : Radeon 530
OS : Ubuntu 18.10 Budgie
Using the latest AMDVLK GPU driver (12.12 release) I get garbled graphics.
Here are the examples(I mostly use LInux for emulators):
Dolphin:
![2019-01-03 00-31-54](https://user-images.githubusercontent.com/33392696/50616381-eba66000-0ef0-11e9-912a-b6a86a6b28cd.png)
RPCS3:
![2019-01-03 00-46-32](https://user-images.githubusercontent.com/33392696/50616439-34f6af80-0ef1-11e9-8cf6-45b00065cc8c.png)
Only the PPSSPP emulator worked correctly with the driver.
Thanks.

**Comment by Alexander88207** [comment] 2019-01-03 16:11
@MojoJojoDojo Mesa works?

**Comment by MojoJojoDojo** [comment] 2019-01-08 11:52
Yes RADV works but I wanted to do a comparison between them.

**Comment by Cx64** [comment] 2019-01-24 17:23
![vulkan-smoketest](https://user-images.githubusercontent.com/47005962/51695965-9d264600-2004-11e9-8979-6a517d00b4a4.png)

I've the very same problem with vulkan-smoketest :
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mars LE [Radeon HD 8530M / R5 M240] (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Mars LE [Radeon HD 8530M / R5 M240]
	Flags: bus master, fast devsel, latency 0, IRQ 44
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f7c00000 (64-bit, non-prefetchable) [size=256K]
	I/O ports at d000 [size=256]
	Expansion ROM at f7c40000 [disabled] [size=128K]
	Kernel driver in use: amdgpu
Kernel 4.20.3-042003-generic #201901171122 SMP Thu Jan 17 16:25:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux.
What to do next ?
Thanks in advance!

**Comment by MojoJojoDojo** [comment] 2019-01-24 18:12
I wonder if thats why Vulkan stopped working on Windows as well.
I can only use it with my Intel GPU.

**Comment by jinjianrong** [comment] 2019-01-25 00:31
@MojoJojoDojo we can't reproduce the issue with RPCS3 emulator-  jojo bizarre adventure. could you provide renderdoc trace?

**Comment by MojoJojoDojo** [comment] 2019-01-25 18:47
@jinjianrong First time I do this i hope i did it right.
[jojo.zip](https://github.com/GPUOpen-Drivers/AMDVLK/files/2797398/jojo.zip)

**Comment by Cx64** [comment] 2019-01-25 20:39
@jinjianrong here my renderdoc trace for vulkan-smoketest, hope this help.
Thanks
luca
[vulkan-smoketestlogs.zip](https://github.com/GPUOpen-Drivers/AMDVLK/files/2797803/vulkan-smoketestlogs.zip)

**Comment by jinjianrong** [comment] 2019-01-30 07:00
@Cx64 does the vulkan-smoketestlogs.zip reproduce the issue on your system? it runs well on our system. could you check if the firmware needs to be updated on your system as talked here: https://github.com/GPUOpen-Drivers/AMDVLK/issues/50#issuecomment-441206916 ?

**Comment by jinjianrong** [comment] 2019-01-30 07:13
@Cx64 we see a black image with the jojo.zip trace, seems not same with the issue you reported. what do you see with the trace on your system?

**Comment by MojoJojoDojo** [comment] 2019-01-30 07:51
![2019-01-30 09-50-59](https://user-images.githubusercontent.com/33392696/51966245-a5eba180-2474-11e9-8fec-c7d512181dbe.png)

**Comment by Cx64** [comment] 2019-01-30 08:20
> @Cx64 does the vulkan-smoketestlogs.zip reproduce the issue on your system? it runs well on our system. could you check if the firmware needs to be updated on your system as talked here: [#50 (comment)](https://github.com/GPUOpen-Drivers/AMDVLK/issues/50#issuecomment-441206916) ?

Yes I'm able to reproduce the same problem as you can see from the screenshot.
I'm on Ubuntu 18.04 with kernel 4.20.5-042005-generic, amdvlk_2019.Q1.4, latest firmware, more detail on info.txt and kernel.log .
What I can do next ? 
Thanks in advance!
![renderdoc](https://user-images.githubusercontent.com/47005962/51967656-2a87f100-2470-11e9-92b9-b65ee8d6fe69.png)
[info.txt](https://github.com/GPUOpen-Drivers/AMDVLK/files/2811543/info.txt)
[kernel.log](https://github.com/GPUOpen-Drivers/AMDVLK/files/2811544/kernel.log)

**Comment by MojoJojoDojo** [comment] 2019-01-30 08:31
I will give more info on my GPU as well:
lspci -vnn | grep -i AMD
01:00.0 Display controller [0380]: Advanced Micro Devices, Inc. [AMD/ATI] Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445] [1002:6900] (rev c1)
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

vulkaninfo | grep -i AMD
		GPU id       : 0 (AMD RADV ICELAND (LLVM 9.0.0))
		GPU id       : 2 (Unknown AMD GPU)
		GPU id       : 0 (AMD RADV ICELAND (LLVM 9.0.0))
		GPU id       : 2 (Unknown AMD GPU)
		GPU id       : 0 (AMD RADV ICELAND (LLVM 9.0.0))
		GPU id       : 2 (Unknown AMD GPU)
		GPU id       : 0 (AMD RADV ICELAND (LLVM 9.0.0))
		GPU id       : 2 (Unknown AMD GPU)
		GPU id       : 0 (AMD RADV ICELAND (LLVM 9.0.0))
		GPU id       : 2 (Unknown AMD GPU)
GPU id       : 0 (AMD RADV ICELAND (LLVM 9.0.0))
GPU id       : 2 (Unknown AMD GPU)
			AMD RADV ICELAND (LLVM 9.0.0) (ID: 0)
			Unknown AMD GPU (ID: 0)
	deviceName     = AMD RADV ICELAND (LLVM 9.0.0)
	VK_AMD_draw_indirect_count          : extension revision  1
	VK_AMD_gcn_shader                   : extension revision  1
	VK_AMD_shader_core_properties       : extension revision  1
	VK_AMD_shader_info                  : extension revision  1
	VK_AMD_shader_trinary_minmax        : extension revision  1
	deviceName     = Unknown AMD GPU
	VK_AMD_buffer_marker                : extension revision  1
	VK_AMD_draw_indirect_count          : extension revision  1
	VK_AMD_gcn_shader                   : extension revision  1
	VK_AMD_gpa_interface                : extension revision  1
	VK_AMD_memory_overallocation_behavior: extension revision  1
	VK_AMD_mixed_attachment_samples     : extension revision  1
	VK_AMD_negative_viewport_height     : extension revision  1
	VK_AMD_rasterization_order          : extension revision  1
	VK_AMD_shader_ballot                : extension revision  1
	VK_AMD_shader_core_properties       : extension revision  1
	VK_AMD_shader_explicit_vertex_parameter: extension revision  1
	VK_AMD_shader_fragment_mask         : extension revision  1
	VK_AMD_shader_image_load_store_lod  : extension revision  1
	VK_AMD_shader_info                  : extension revision  1
	VK_AMD_shader_trinary_minmax        : extension revision  1
	VK_AMD_texture_gather_bias_lod      : extension revision  1

**Comment by Cx64** [comment] 2019-02-28 10:13
Hi, I've just installed the latest version amdvlk_2019.Q1.6_amd64.deb but the problem still persist, mesa works ok. @jinjianrong any hope that this will be fixed anytime soon ?
Thanks!

**Comment by MojoJojoDojo** [comment] 2019-03-01 12:58
I think they won't fix it that easily because its specific to certain GPU's.
But i narrowed it down to Iceland or Radeon™ M200/M300/M400 Series.

**Comment by jinjianrong** [comment] 2019-03-04 06:25
Unfortunately, we have not reproduced the issue yet. 
@MojoJojoDojo according to the vulkaninfo you provided, looks like your system is running with both RADV and AMDVLK, could you remove RADV's JSON file and try again? 

@Cx64 could you provide the vulkaninfo log?

**Comment by Cx64** [comment] 2019-03-04 09:09
> Unfortunately, we have not reproduced the issue yet.
> @MojoJojoDojo according to the vulkaninfo you provided, looks like your system is running with both RADV and AMDVLK, could you remove RADV's JSON file and try again?
> 
> @Cx64 could you provide the vulkaninfo log?

Hi @jinjianrong 
you can find all the log here:
https://github.com/GPUOpen-Drivers/AMDVLK/issues/72#issuecomment-457719634

Let me if I can help further !
Thanks,
luca

**Comment by MojoJojoDojo** [comment] 2019-03-07 10:06
I think this issue is the same as issue #54

**Comment by bobeick87** [comment] 2019-03-13 20:12
Hi all,
I have a Radeon HD8670m (Southern Island, Hainan/Mars) and the AMDVLK produces the same kind of garbled graphics described here by you guys. It seems most of the driver works fine but just something messes up when the images get rendered producing a mess. In windows Vulkan works great with this card. Back to linux with Mesa the vulkan (intel) works ok but it's slow.

**Comment by jinjianrong** [comment] 2019-03-14 03:19
@bobeick87 are there two GPUs in your system: one intel's integrated GPU + one Radeon HD8670m? Does the issue happen when rendering with HD8670m but present on Intel's integrated GPU?

**Comment by bobeick87** [comment] 2019-03-15 04:04
Hi jinjianrong, yes I have the integrated intel 4400 HD (Core i5 4200U Haswell) and the discrete radeon HD8670M. I have compiled and build AMDVLK via the available instructions and seems fine. My system is Ubuntu 18.10 Kernel is 5.0.1, and am using AMDGPU kernel module. I tested Vulkan with the emulator Dolphin, and vulkan-cube (vulkan sdk x.101) and both render strange graphics and give no error messages. The rendering is fine if I install and run tests on the mesa-vulkan driver (which uses the intel integrated). It is a shame not to be able to use vulkan on the discrete.

**Comment by MojoJojoDojo** [comment] 2019-03-15 12:04
I am here to report that the latest Windows driver fixed Vulkan on my AMD GPU.
But now I cant access my Intel GPU's Vulkan capabilities  (not a big loss).
Now that its fixed on Windows I dont have to relay on Linux for the RADV driver but I will check if it works there later.

**Comment by seesturm** [comment] 2019-03-28 20:58
I have the same problem (garbled picture) on my host with two Vega56 GPUs. If I remove one of them vulkan-smoketest works.

**Comment by Pik-a-boo** [comment] 2019-04-01 20:51
Same problem as others - corrupted graphics .
I have a dual Intel-AMD GPU system.
Looks like the problem is with Hybrid Graphics?
From the last comment and other comments here.
RADV driver works as intended.

**Comment by seesturm** [comment] 2019-04-11 20:28
I managed to get AMDVLK working for me by means of putting into ~/.config/amdPalSettings.cfg:
`EnumPreferredDeviceIndex,0`
Don't know if this could help the users with hybrid graphics here since I have two identical cards (Vega56).

**Comment by Pik-a-boo** [comment] 2019-04-12 17:24
@seesturm putting what where?
Can you give more details?

**Comment by seesturm** [comment] 2019-04-12 19:35
@Pik-a-boo: I created a config file "amdPalSettings.cfg" in "/home/seesturm/.config" with a single line "EnumPreferredDeviceIndex,0". If there already happens to be a config file with the same name in your ".config" folder then you could add the line to the existing config file.

**Comment by jozefkucia** [comment] 2019-05-05 08:06
The same issue on machine with Intel HD Graphics 630 and Radeon RX Vega 56.

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] (rev c3)

**Comment by VadikLeshy** [comment] 2019-08-07 21:36
I also have the same issue on my Laptop with AMD APU A12 + Rareon R7 M440.

$ lspci | grep -i radeon
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Wani [Radeon R5/R6/R7 Graphics] (rev c9)
03:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445] (rev 83)
$ lspci -s 03:00.0 -k
03:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445] (rev 83)
Subsystem: Acer Incorporated [ALI] Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445]
Kernel driver in use: amdgpu
Kernel modules: amdgpu

https://github.com/GPUOpen-Drivers/AMDVLK/issues/54

**Comment by Pik-a-boo** [comment] 2019-10-01 21:25
I cant believe this issue is still a thing.
You think it got fixed but than you find out its only for Navi GPUs.
No legacy support huh.

**Closed** 2019-11-13 14:21 UTC
