### ISSUE TITLE
[Regression] Strange visual corruption when rasterizing to a VkImage that was previously used in a compute shader

### ISSUE THREAD

**Issue by haasn** [GPUOpen-Drivers/AMDVLK#256] opened 2021-11-06 22:29 UTC
See https://github.com/mpv-player/mpv/issues/9389 for context. But basically, I get artifacts like these:

![glitches](https://user-images.githubusercontent.com/1149047/140625159-64f7554a-5351-4beb-a1a3-27e84c37c4ca.png)

This is with blending enabled, but that part seems to be working correctly (though the alpha channel seems to be derived from the same sort of corruption as the rgb color values). I get corruption even with a trivial fragment shader like `void main() { out_color = vec4(0.2, 0.4, 0.6, 1.0);`, in which case it looks more like this:

![glitches-constant](https://user-images.githubusercontent.com/1149047/140625181-a8bd7f4d-2ff0-4d3f-9591-93ae335f909e.png)

This is very much consistent with the color values output by the shader themselves being somehow horrifically mangled/misinterpreted by the hardware. This is very surprising given that it's the rasterization output of a fragment shader, rather than being read anywhere from memory.

The only consistent reproducing circumstance seems to be:

1. Render to a VkImage using `imageStore` from a compute shader.
2. Render to that same VkImage using a fragment shader.

Notably, any other operation involving the VkImage seems to work fine. I can download it again and it will look correct on the host. I can sample from it in other shaders, even other fragment shaders. It's only *rendering* to them that seems to break, and only from fragment shaders.

**Comment by haasn** [comment] 2021-11-06 22:31
I also managed to get corruption like this, by rendering to an image and then blitting (vkCmdCopyImage) it to a different image:

![glitches-wholeframe](https://user-images.githubusercontent.com/1149047/140625593-9819f85b-0449-441d-aca7-cdf2ae00d309.png)

I really have no idea what's going here anymore, other than that it's very broken and only seems to affect AMDVLK.

**Comment by haasn** [comment] 2021-11-06 22:34
Update: This is a regression according to [this comment](https://github.com/mpv-player/mpv/issues/9389#issuecomment-962517250)

**Comment by jinjianrong** [comment] 2022-11-21 11:43
The issue is fixed in 2022.Q3.1 and later release

**Closed by jinjianrong** 2022-11-21 11:43 UTC
