### ISSUE TITLE
V-sync is broken with hybrid graphics laptops

### ISSUE THREAD

**Issue by ghost** [GPUOpen-Drivers/AMDVLK#182] opened 2020-08-23 16:20 UTC
This thing is bothering me for awhile.
I have a dual GPU laptop that contains an AMD GPU (Radeon 530) and an Intel GPU (Intel UHD 620).
If i use the AMDVLK driver and if I use the AMD Vulkan driver on Windows 10 I will get constant tearing no matter what I play/use.
On the RADV driver I get no apperant tearing (or it might be unnoticable to me at least)..
This is stricly an AMD GPU driver issue on Windows at least because if I switch to the Intel driver the tearing is gone.
I know that applying `UseFlipHint,1` might fix it on Linux but I have no idea how could I do the same on the Windows driver (I use it more often).
Thanks.

**Comment by jinjianrong** [comment] 2020-09-14 08:50
@MojoJojoDojo what version of Windows driver do you use ? could you provide detailed steps to reproduce the issue on Windows?

**Comment by MojoJojoDojo** [comment] 2020-09-15 20:55
@jinjianrong I have the latest AMD driver on Windows 10 which is 20.8.3 (I also use the latest Intel GPU driver as well).
This basically happens with every game/app that uses Vulkan.
For example on RetroArch you could see tearing while you move on the menu when using it's Vulkan driver.
If that's not enough I tried running Doom 64 with the Vulkan renderer and got tearing there as well.
With both examples I get tearing with v-sync on and I got both on Steam.
While I use the Intel GPU the tearing is gone (I remember that I did get tearing before but i guess it's got fixed?).
I know I can use other renderers for both but I often get the best performance while using the Vulkan renderer.

**Comment by MojoJojoDojo** [comment] 2020-10-11 11:29
Forgot to mention that the situation happens on both windowed and fullscreen.

**Comment by MojoJojoDojo** [comment] 2020-10-28 16:42
Uploaded 2 videos of this issue here : https://gofile.io/d/kWwjLe
Also reported this on AMD's bug reporting tool on Windows 10.
I hope it gets fixed soon...

**Comment by AtifArshad1995** [comment] 2020-11-25 07:22
I have the exact same issue as @MojoJojoDojo and by coincidence, I have a Dell laptop with same GPUs, AMD Radeon 530 and Intel UHD 620 (so there is a chance that I have the same Laptop as Mojo). I get screen tearing on the side of the screen whenever I use AMD GPU with any thing using Vulkan. This issue has been present quite a while now.

I am using the current latest AMD drivers (20.9.1) right now and using Windows 10.

**Comment by MojoJojoDojo** [comment] 2020-11-25 08:35
> I have the exact same issue as @MojoJojoDojo and by coincidence, I have a Dell laptop with same GPUs, AMD Radeon 530 and Intel UHD 620 (so there is a chance that I have the same Laptop as Mojo). I get screen tearing on the side of the screen whenever I use AMD GPU with any thing using Vulkan. This issue has been present quite a while now.
> 
> I am using the current latest AMD drivers (20.9.1) right now and using Windows 10.

I thought I was seeing things and I am the only one.
Looking at your profile I bet you also tried some Doom ports and games with Vulkan.

**Comment by AtifArshad1995** [comment] 2020-11-25 10:35
Yes. I have used GZDoom, vkQuake, vkQuake2, Yamagi Quake 2 (test builds with Vulkan renderer).

They all show tearing on side of the screen (usually the left side of the screen).

**Comment by MojoJojoDojo** [comment] 2020-11-25 12:57
Yeah same its the left side (top-left?) of the screen.
For some reason I can't reproduce it when recording any gameplay but it will still show some sort of tearing with the videos I uploaded above.
Just giving more info here so it could help devs fix it.

**Comment by AtifArshad1995** [comment] 2020-11-25 13:10
Yup. Top left side of screen for me as well.

**Comment by MojoJojoDojo** [comment] 2020-11-25 14:13
Researched the issue a bit now and I see this issue also happens on win10 and Dell laptops in general :
https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/219789/diagonal-screen-tearing-issues-on-gtx-860m870m960m/

I still think its somewhat related to how the hybrid graphics on the laptop works.
That's all I got for now though.

**Comment by MojoJojoDojo** [comment] 2021-01-08 19:15
Tried again on the latest Windows driver and I see nothing changed.
Also noticed that the AMDVLK driver is noticeably slower then the RADV one (RADV is 2x more faster unthrottled on the Dolphin emulator) and exhibits stutters and frame drops on various apps.
Might create a seperate issue on that.

**Comment by MojoJojoDojo** [comment] 2021-03-20 17:08
Still happens on the latest drivers.
Also changed the name of the issue to something more appropriate.

**Comment by MojoJojoDojo** [comment] 2021-06-22 11:34
And now the Windows driver is considered legacy so that means that the issue would never get fixed on Windows.
Shame for me and @AtifArshad1995

**Closed** 2024-05-22 05:44 UTC
